name: Bot ações telegram

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"
    - cron: "0 15 * * *"
    - cron: "0 17 * * *"
    - cron: "0 19 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script
        run: python bot.py
